=== zpGame/simpleflow/simpleflow-core/src/main/resources/xsd/simple-flow-xml.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://simple-flow.hunk.com"
           xmlns="http://simple-flow.hunk.com"
           elementFormDefault="qualified">

    <xs:element name="choose">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="when" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="start">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="choose" minOccurs="0"/>
            </xs:sequence>
            <xs:attribute name="beanId" use="required"  type="xs:string"/>
            <xs:attribute name="nodeDesc" type="xs:string"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="node">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="choose" minOccurs="0"/>
            </xs:sequence>
            <xs:attribute name="beanId" use="required"  type="xs:string"/>
            <xs:attribute name="nodeDesc" type="xs:string"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="end">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="choose" minOccurs="0"/>
            </xs:sequence>
            <xs:attribute name="beanId" use="required"  type="xs:string"/>
            <xs:attribute name="nodeDesc" type="xs:string"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="nodes">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="start" maxOccurs="unbounded"/>
                <xs:element ref="node" maxOccurs="unbounded"/>
                <xs:element ref="end" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="simpleFlow">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="nodes"/>
            </xs:sequence>
            <xs:attribute name="flowName" use="required" type="xs:string"/>
            <xs:attribute name="flowDesc" type="xs:string"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="when">
        <xs:complexType>
            <xs:attribute name="condition" type="xs:string"/>
            <xs:attribute name="to" use="required" type="xs:string"/>
            <xs:attribute name="conditionDesc" type="xs:string"/>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== zpGame/simpleflow/simpleflow-testcase/src/test/resources/flow/xml/sampleByXml.xml
<?xml version="1.0" encoding="UTF-8" ?>
<simpleFlow flowName="testProcess" flowDesc="测试流程" xmlns="http://simple-flow.hunk.com"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="http://simple-flow.hunk.com simple-flow-xml.xsd">
    <nodes>
        <start beanId="checkFlow" nodeDesc="参数校验">
            <choose>
                <when condition="${ paramOne} eq 'true' " to="flowOne" conditionDesc="流程1"/>
                <when condition=" empty (${paramOne}) or ${paramOne} ne 'true' " to="flowTwo" conditionDesc="流程2"/>
            </choose>
        </start>
        <node beanId="flowOne" nodeDesc="流程1">
            <choose>
                <when condition="${ paramTwo} eq '1'" to="flowThree" conditionDesc="流程3"/>
                <when condition="${ paramTwo} eq '2'" to="flowFour" conditionDesc="流程4"/>
            </choose>
        </node>
        <node beanId="flowTwo" nodeDesc="流程2">
            <choose>
                <when condition="${ paramTwo} eq '1' " to="flowThree" conditionDesc="流程3"/>
                <when condition="${ paramTwo} eq '2' " to="flowFour" conditionDesc="流程4"/>
            </choose>
        </node>
        <node beanId="flowThree" nodeDesc="流程3">
            <choose>
                <when condition="${ paramOne} eq 'true' " to="flowEnd" conditionDesc="流程结束"/>
            </choose>
        </node>
        <node beanId="flowFour" nodeDesc="流程4">
            <choose>
                <when condition="${ paramOne} eq 'true' " to="flowEnd" conditionDesc="流程结束"/>
            </choose>
        </node>
        <end beanId="flowEnd" nodeDesc="流程结束"/>
    </nodes>
</simpleFlow>
