=== zpGame/simpleflow/simpleflow-core/src/main/resources/xsd/simple-flow-xml2.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://simple-flow.hunk.com"
           xmlns="http://simple-flow.hunk.com"
           elementFormDefault="qualified">

    <xs:element name="line">
        <xs:complexType>
            <xs:attribute name="conditionDesc" type="xs:string"/>
            <xs:attribute name="condition" type="xs:string"/>
            <xs:attribute name="from" use="required" type="xs:string"/>
            <xs:attribute name="to" use="required" type="xs:string"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="lines">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="line" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="start">
        <xs:complexType>
            <xs:attribute name="beanId" use="required" type="xs:string"/>
            <xs:attribute name="nodeDesc" type="xs:string"/>
            <xs:attribute name="preEvent" type="xs:string"/>
            <xs:attribute name="afterEvent" type="xs:string"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="node">
        <xs:complexType>
            <xs:attribute name="beanId" use="required" type="xs:string"/>
            <xs:attribute name="nodeDesc" type="xs:string"/>
            <xs:attribute name="preEvent" type="xs:string"/>
            <xs:attribute name="afterEvent" type="xs:string"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="end">
        <xs:complexType>
            <xs:attribute name="beanId" use="required" type="xs:string"/>
            <xs:attribute name="nodeDesc" type="xs:string"/>
            <xs:attribute name="preEvent" type="xs:string"/>
            <xs:attribute name="afterEvent" type="xs:string"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="nodes">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="start" maxOccurs="unbounded"/>
                <xs:element ref="node" maxOccurs="unbounded"/>
                <xs:element ref="end" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="simpleFlow">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="nodes"/>
                <xs:element ref="lines"/>
            </xs:sequence>
            <xs:attribute name="flowName" use="required" type="xs:string"/>
            <xs:attribute name="flowDesc" type="xs:string"/>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== zpGame/simpleflow/simpleflow-testcase/src/test/resources/flow/xml2/sampleNoCondition.xml
<?xml version="1.0" encoding="UTF-8" ?>
<simpleFlow flowName="testProcessNoCondition" flowDesc="测试流程" xmlns="http://simple-flow.hunk.com"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="http://simple-flow.hunk.com simple-flow-xml2.xsd">
    <nodes>
        <start beanId="flowNoConditionOne" nodeDesc="流程1" preEvent=""/>
        <node beanId="flowNoConditionTwo" nodeDesc="流程2"/>
        <end beanId="flowNoConditionThree" nodeDesc="流程3"/>
    </nodes>

    <lines>
        <line conditionDesc="流程1" from="flowNoConditionOne" to="flowNoConditionTwo"/>
        <line conditionDesc="流程1" from="flowNoConditionTwo" to="flowNoConditionThree"/>
    </lines>
</simpleFlow>

=== zpGame/simpleflow/simpleflow-testcase/src/test/resources/flow/xml2/sampleByXml.xml
<?xml version="1.0" encoding="UTF-8" ?>
<simpleFlow flowName="testProcess" flowDesc="测试流程" xmlns="http://simple-flow.hunk.com"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="http://simple-flow.hunk.com simple-flow-xml2.xsd">
    <nodes>
        <start beanId="checkFlow" nodeDesc="参数校验"/>
        <node beanId="flowOne" nodeDesc="流程1"/>
        <node beanId="flowTwo" nodeDesc="流程2"/>
        <node beanId="flowThree" nodeDesc="流程3"/>
        <node beanId="flowFour" nodeDesc="流程4"/>
        <end beanId="flowEnd" nodeDesc="流程结束"/>
    </nodes>

    <lines>
        <line conditionDesc="流程1" condition="${ paramOne} eq 'true' " from="checkFlow" to="flowOne"/>
        <line conditionDesc="流程3" condition="${ paramTwo} eq '1'" from="flowOne" to="flowThree"/>
        <line conditionDesc="流程4" condition="${ paramTwo} eq '2'" from="flowOne" to="flowFour"/>

        <line conditionDesc="流程2" condition=" empty (${paramOne}) or ${paramOne} ne 'true' " from="checkFlow" to="flowTwo"/>
        <line conditionDesc="流程3" condition="${ paramTwo} eq '1' " from="flowTwo" to="flowThree"/>
        <line conditionDesc="流程4" condition="${ paramTwo} eq '2' " from="flowTwo" to="flowFour"/>

        <line conditionDesc="流程结束" condition="${ paramOne} eq 'true' " from="flowThree" to="flowEnd"/>
        <line conditionDesc="流程结束" condition="${ paramOne} eq 'true' " from="flowFour" to="flowEnd"/>
    </lines>
</simpleFlow>
